# Generated by Django 3.1.2 on 2020-11-28 13:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201128_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='link_gerb',
            field=models.CharField(default='', max_length=500, verbose_name='Герб'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexiq',
            name='index_iq',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=5, verbose_name='Итоговый индекс IQ'),
        ),
    ]
