# Generated by Django 3.1.2 on 2020-11-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201128_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='link_gerb',
            field=models.CharField(blank=True, max_length=500, verbose_name='Герб'),
        ),
    ]
