# Generated by Django 3.1.2 on 2020-11-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_city_square'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='square',
        ),
    ]
